package com.freeuni.quizwebsite.model;

public enum QuestionType {

    QUESTION_RESPONSE,
    QUESTION_RESPONSE_MULTIPLE_ANSWER_UNORDERED,
    QUESTION_RESPONSE_MULTIPLE_ANSWER_ORDERED,
    FILL_IN_BLANK,
    PICTURE_RESPONSE,
    MULTIPLE_CHOICE,
    MULTIPLE_CHOICE_MULTIPLE_ANSWER

}
